---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data


```{r setup, include=FALSE}
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
monitoringData<-read.csv(unz("activity.zip", "activity.csv"),col.names = c("steps","date","interval"),na.strings = NA)
monitoringData[,2]<-as.data.frame(strptime(monitoringData[,2],format = "%Y-%m-%d"))
aggregateStepsByDay<-aggregate(steps ~ date, monitoringData, sum)
aggregateStepsByDayAndInterval<-aggregate(steps ~  interval, monitoringData, mean)
```
```{r}
 png(file="Histogram_of_steps_each_day.png",height=480,width = 480)
 fig1<-hist(aggregateStepsByDay$steps,
        xlab = "Steps",
        col="red",
        main = "Steps per day"
   )
print(fig1)
dev.off()

meanSteps<-mean(aggregateStepsByDay$steps)
medianSteps<-median(aggregateStepsByDay$steps)

## What is mean total number of steps taken per day?
print(paste("Mean of Steps per day:",meanSteps))
print(paste("Median of Steps per day:",medianSteps))


## What is the average daily activity pattern?
png(file="Time_series_average_steps_taken.png",height=480,width = 480)
fig2<-plot( aggregateStepsByDayAndInterval$interval,
         aggregateStepsByDayAndInterval$steps,
          ylab = "Steps",
          type = "l",
          xlab="Interval",
          main = "Average Daily Activity Pattern",
         col="darkred"
    )
print(fig2)
dev.off()
aggregateStepsByDayAndInterval[which.max(aggregateStepsByDayAndInterval$steps),]

nrow(monitoringData[is.na(monitoringData$steps),])

## Imputing missing values

monitoringDataNoNAs<-monitoringData
monitoringDataNoNAs[is.na(monitoringDataNoNAs)]<-0

nrow(monitoringDataNoNAs[is.na(monitoringDataNoNAs$steps),])

noNAaggregageStepsByDay<-aggregate(steps ~ date, monitoringDataNoNAs, sum)

 png(file="Histogram_of_steps_each_day_after_imputing.png",height=480,width = 480)
 fig3<-hist(noNAaggregageStepsByDay$steps,
        xlab = "Steps",
        col="blue",
        main = "Steps per day no NA's"
   )
 print(fig3)
dev.off()
noNAmeanSteps<-mean(noNAaggregageStepsByDay$steps)
noNAmedianSteps<-median(noNAaggregageStepsByDay$steps)
print(paste("Mean of Steps per day:",noNAmeanSteps))
print(paste("Median of Steps per day:",noNAmedianSteps))

#yes there is a difference after imputing the dataset.


## Are there differences in activity patterns between weekdays and weekends?

Weektype<-as.factor(ifelse(weekdays(monitoringDataNoNAs$date)=="Saturday" | weekdays(monitoringDataNoNAs$date)=="Sunday","Weekend","Weekday"))

names(Weektype)<-"Weektype"

newNoNaDataSet<-cbind(monitoringDataNoNAs,Weektype)

stepsByDayType<-aggregate(steps ~ interval + Weektype, newNoNaDataSet, mean)
 png(file="Panel_plot_compare_average_steps_per_5-minute_interval_across_weekdays_and_weekends.png",height=480,width = 480)
 g<-ggplot(stepsByDayType, aes(interval,steps, color = Weektype)) +
        geom_path() +  
        facet_grid(. ~ Weektype ) +
        labs(x="Interval", y="Steps", title="Avgerage Daily Steps by Weektype")
   
    print(g)
dev.off()
    
```
